remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Duber Alexander Carmona Marin
submodulo: Introdución a la programación
periodo: 2023-2
foto: https://firebasestorage.googleapis.com/v0/b/desarrollador-cf08c.appspot.com/o/foto.jpg?alt=media&token=cd945907-06a4-45bf-a8d9-0f779d847c58

